### ISSUE TITLE
create kaboom game

### ISSUE THREAD

**Issue by CraigThomasson** [CraigThomasson/team-5-music-game-#13]

**Comment by CraigThomasson** [comment]
- [ ] - create core game logic
- [ ] - create menu screen/scene
- [ ] - add stage 1 game
- [ ] add stage 2 game
- [ ] add stage 3 game 
- [ ] add stage 4 game
- [ ] add stage 5 game

**Comment by Koko-66** [comment]
Decided not to use kaboom
